steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/soil-moisture-api', '.']

  # Step 2: Push the Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/soil-moisture-api']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'soil-moisture-api',
      '--image', 'gcr.io/$PROJECT_ID/soil-moisture-api',
      '--platform', 'managed',
      '--region', 'asia-southeast1',
      '--allow-unauthenticated',
      '--memory', '512Mi',
      '--cpu', '1'
    ]

images:
  - 'gcr.io/$PROJECT_ID/soil-moisture-api'
